Use the dummy intl lib from TV, if the installed is not usable and use the patched conio.o for DJGPP when needed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -806,27 +806,28 @@ if test "$rhide_OS" = DJGPP; then
 fi
 
 
-echo $ac_n "checking for bindtextdomain in -lc""... $ac_c" 1>&6
-echo "configure:811: checking for bindtextdomain in -lc" >&5
-ac_lib_var=`echo c'_'bindtextdomain | sed 'y%./+-%__p_%'`
+if test "$rhide_OS" = DJGPP; then
+  echo $ac_n "checking for gettext in -lc""... $ac_c" 1>&6
+echo "configure:812: checking for gettext in -lc" >&5
+ac_lib_var=`echo c'_'gettext | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   ac_save_LIBS="$LIBS"
 LIBS="-lc  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 819 "configure"
+#line 820 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
     builtin and then its argument prototype would still apply.  */
-char bindtextdomain();
+char gettext();
 
 int main() {
-bindtextdomain()
+gettext()
 ; return 0; }
 EOF
-if { (eval echo configure:830: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:831: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -841,57 +842,12 @@ LIBS="$ac_save_LIBS"
 fi
 if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
   echo "$ac_t""yes" 1>&6
-  LIB_INTL=
+  CONIO_PATCH=$abs_srcdir/conio.o
 else
   echo "$ac_t""no" 1>&6
-LIB_INTL=no
+CONIO_PATCH=
 fi
 
-
-if test "x$LIB_INTL" = xno; then
-  echo $ac_n "checking needed libs for gettext""... $ac_c" 1>&6
-echo "configure:854: checking needed libs for gettext" >&5
-  rh_save_LIBS="$LIBS"
-  LIBS="-lintl $LIBS"
-  cat > conftest.$ac_ext <<EOF
-#line 858 "configure"
-#include "confdefs.h"
-#include <libintl.h>
-  #include <stdio.h>
-int main() {
-printf(gettext("test"))
-; return 0; }
-EOF
-if { (eval echo configure:866: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
-  rm -rf conftest*
-  LIB_INTL=intl
-else
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-fi
-rm -f conftest*  LIBS="$rh_save_LIBS"
-  if test "x$LIB_INTL" = x; then
-    rh_save_LIBS="$LIBS"
-    LIBS="-lintl -liconv $LIBS"
-    cat > conftest.$ac_ext <<EOF
-#line 878 "configure"
-#include "confdefs.h"
-#include <libintl.h>
-  #include <stdio.h>
-int main() {
-printf(gettext("test"))
-; return 0; }
-EOF
-if { (eval echo configure:886: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
-  rm -rf conftest*
-  LIB_INTL="intl iconv"
-else
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-fi
-rm -f conftest*    LIBS="$rh_save_LIBS"
-  fi
-  echo "$ac_t""$LIB_INTL" 1>&6
 fi
 
 
@@ -904,7 +860,7 @@ $DJDIR/include/rhtvision \
 /usr/include/rhtvision"
 
 echo $ac_n "checking for Turbo Vision header files""... $ac_c" 1>&6
-echo "configure:908: checking for Turbo Vision header files" >&5
+echo "configure:864: checking for Turbo Vision header files" >&5
 if eval "test \"`echo '$''{'rh_cv_path_TV_INC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -935,8 +891,13 @@ fi
 TV_INC="$rh_cv_path_TV_INC"
 echo "$ac_t""$TV_INC" 1>&6
 if test "$TV_INC" = no; then
-  { echo "configure: error: Could not find Turbo Vision header files.
-  Please give me a hint by setting the variable TV_INC" 1>&2; exit 1; }
+  if test "x" = x; then
+    { echo "configure: error: Could not find Turbo Vision header files.
+    Please give me a hint by setting the variable TV_INC" 1>&2; exit 1; }
+  else
+    echo "configure: warning: Could not find Turbo Vision header files.
+    " 1>&2
+  fi
 fi
 
 
@@ -944,7 +905,7 @@ TV_OBJ_SEARCH="$TV_INC/../`echo $rhide_OS | sed s,Linux,linux,g` \
 $TV_INC/../../lib"
 
 echo $ac_n "checking for Turbo Vision libraray""... $ac_c" 1>&6
-echo "configure:948: checking for Turbo Vision libraray" >&5
+echo "configure:909: checking for Turbo Vision libraray" >&5
 if eval "test \"`echo '$''{'rh_cv_path_TVOBJ'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -975,8 +936,13 @@ fi
 TVOBJ="$rh_cv_path_TVOBJ"
 echo "$ac_t""$TVOBJ" 1>&6
 if test "$TVOBJ" = no; then
-  { echo "configure: error: Could not find Turbo Vision libraray.
-  Please give me a hint by setting the variable TVOBJ" 1>&2; exit 1; }
+  if test "x" = x; then
+    { echo "configure: error: Could not find Turbo Vision libraray.
+    Please give me a hint by setting the variable TVOBJ" 1>&2; exit 1; }
+  else
+    echo "configure: warning: Could not find Turbo Vision libraray.
+    " 1>&2
+  fi
 fi
 
 
@@ -986,7 +952,7 @@ $DJDIR/contrib/setedit \
 /usr/src/setedit"
 
 echo $ac_n "checking for SET's editor sources""... $ac_c" 1>&6
-echo "configure:990: checking for SET's editor sources" >&5
+echo "configure:956: checking for SET's editor sources" >&5
 if eval "test \"`echo '$''{'rh_cv_path_SETSRC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1017,14 +983,19 @@ fi
 SETSRC="$rh_cv_path_SETSRC"
 echo "$ac_t""$SETSRC" 1>&6
 if test "$SETSRC" = no; then
-  { echo "configure: error: Could not find SET's editor sources.
-  Please give me a hint by setting the variable SETSRC" 1>&2; exit 1; }
+  if test "x" = x; then
+    { echo "configure: error: Could not find SET's editor sources.
+    Please give me a hint by setting the variable SETSRC" 1>&2; exit 1; }
+  else
+    echo "configure: warning: Could not find SET's editor sources.
+    " 1>&2
+  fi
 fi
 
 
 
 echo $ac_n "checking for SET's editor libraries""... $ac_c" 1>&6
-echo "configure:1028: checking for SET's editor libraries" >&5
+echo "configure:999: checking for SET's editor libraries" >&5
 if eval "test \"`echo '$''{'rh_cv_path_SETOBJ'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1055,8 +1026,109 @@ fi
 SETOBJ="$rh_cv_path_SETOBJ"
 echo "$ac_t""$SETOBJ" 1>&6
 if test "$SETOBJ" = no; then
-  { echo "configure: error: Could not find SET's editor libraries.
-  Please give me a hint by setting the variable SETOBJ" 1>&2; exit 1; }
+  if test "x" = x; then
+    { echo "configure: error: Could not find SET's editor libraries.
+    Please give me a hint by setting the variable SETOBJ" 1>&2; exit 1; }
+  else
+    echo "configure: warning: Could not find SET's editor libraries.
+    " 1>&2
+  fi
+fi
+
+
+SET_SPECIAL_LDFLAGS=
+echo $ac_n "checking for bindtextdomain in -lc""... $ac_c" 1>&6
+echo "configure:1042: checking for bindtextdomain in -lc" >&5
+ac_lib_var=`echo c'_'bindtextdomain | sed 'y%./+-%__p_%'`
+if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  ac_save_LIBS="$LIBS"
+LIBS="-lc  $LIBS"
+cat > conftest.$ac_ext <<EOF
+#line 1050 "configure"
+#include "confdefs.h"
+/* Override any gcc2 internal prototype to avoid an error.  */
+/* We use char because int might match the return type of a gcc2
+    builtin and then its argument prototype would still apply.  */
+char bindtextdomain();
+
+int main() {
+bindtextdomain()
+; return 0; }
+EOF
+if { (eval echo configure:1061: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=yes"
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=no"
+fi
+rm -f conftest*
+LIBS="$ac_save_LIBS"
+
+fi
+if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+  LIB_INTL=
+else
+  echo "$ac_t""no" 1>&6
+LIB_INTL=no
+fi
+
+
+if test "x$LIB_INTL" = xno; then
+  echo $ac_n "checking needed libs for gettext""... $ac_c" 1>&6
+echo "configure:1085: checking needed libs for gettext" >&5
+  rh_save_LIBS="$LIBS"
+  LIBS="-lintl $LIBS"
+  cat > conftest.$ac_ext <<EOF
+#line 1089 "configure"
+#include "confdefs.h"
+#include <libintl.h>
+  #include <stdio.h>
+int main() {
+printf(gettext("test"))
+; return 0; }
+EOF
+if { (eval echo configure:1097: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  LIB_INTL=intl
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+fi
+rm -f conftest*  LIBS="$rh_save_LIBS"
+  if test "x$LIB_INTL" = xno; then
+    rh_save_LIBS="$LIBS"
+    LIBS="-lintl -liconv $LIBS"
+    cat > conftest.$ac_ext <<EOF
+#line 1109 "configure"
+#include "confdefs.h"
+#include <libintl.h>
+  #include <stdio.h>
+int main() {
+printf(gettext("test"))
+; return 0; }
+EOF
+if { (eval echo configure:1117: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  LIB_INTL="intl iconv"
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+fi
+rm -f conftest*    LIBS="$rh_save_LIBS"
+  fi
+  echo "$ac_t""$LIB_INTL" 1>&6
+fi
+if test "x$LIB_INTL" = xno; then
+  echo "configure: warning: found not usable library providing gettext,
+ using now a dummy one" 1>&2
+  LIB_INTL=tvfintl
+  SET_SPECIAL_LDFLAGS="$SET_SPECIAL_LDFLAGS -L$TVOBJ/../intl/dummy"
 fi
 
 
@@ -1068,7 +1140,7 @@ $DJDIR/gnu/$gdb_version \
 /usr/src/$gdb_version"
 
 echo $ac_n "checking for GDB sources""... $ac_c" 1>&6
-echo "configure:1072: checking for GDB sources" >&5
+echo "configure:1144: checking for GDB sources" >&5
 if eval "test \"`echo '$''{'rh_cv_path_GDB_SRC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1099,13 +1171,70 @@ fi
 GDB_SRC="$rh_cv_path_GDB_SRC"
 echo "$ac_t""$GDB_SRC" 1>&6
 if test "$GDB_SRC" = no; then
-  { echo "configure: error: Could not find GDB sources.
-  Please give me a hint by setting the variable GDB_SRC" 1>&2; exit 1; }
+  if test "xtrying older version" = x; then
+    { echo "configure: error: Could not find GDB sources.
+    Please give me a hint by setting the variable GDB_SRC" 1>&2; exit 1; }
+  else
+    echo "configure: warning: Could not find GDB sources.
+    trying older version" 1>&2
+  fi
 fi
 
 
+if test "$GDB_SRC" = no; then
+  gdb_version="gdb-5.0"
+
+  GDB_SRC_SEARCH="$abs_srcdir/../$gdb_version \
+  $DJDIR/gnu/$gdb_version \
+  /usr/local/src/$gdb_version \
+  /usr/src/$gdb_version"
+  
+echo $ac_n "checking for GDB sources""... $ac_c" 1>&6
+echo "configure:1194: checking for GDB sources" >&5
+if eval "test \"`echo '$''{'rh_cv_path_GDB_SRC_OLD'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  case "$GDB_SRC_OLD" in
+  /*)
+    rh_cv_path_GDB_SRC_OLD="$GDB_SRC_OLD" # Let the user override the test with a path.
+  ;;
+  ?:/*)
+    rh_cv_path_GDB_SRC_OLD="$GDB_SRC_OLD" # Let the user override the test with a dos path.
+  ;;
+esac
+if test -z $rh_cv_path_GDB_SRC_OLD; then
+  if test "$cross_compiling" = yes; then
+    { echo "configure: error: Cannot check for file existence when cross compiling" 1>&2; exit 1; }
+  else
+    for dir in $GDB_SRC_SEARCH; do
+      if test -r $dir/gdb/main.c; then
+        eval "rh_cv_path_GDB_SRC_OLD=$dir"
+        break;
+       else
+        eval "rh_cv_path_GDB_SRC_OLD=no"
+      fi
+    done    
+  fi
+fi
+
+fi
+GDB_SRC_OLD="$rh_cv_path_GDB_SRC_OLD"
+echo "$ac_t""$GDB_SRC_OLD" 1>&6
+if test "$GDB_SRC_OLD" = no; then
+  if test "x" = x; then
+    { echo "configure: error: Could not find GDB sources.
+    Please give me a hint by setting the variable GDB_SRC_OLD" 1>&2; exit 1; }
+  else
+    echo "configure: warning: Could not find GDB sources.
+    " 1>&2
+  fi
+fi
+
+  GDB_SRC="$GDB_SRC_OLD"
+fi
+
 echo $ac_n "checking GDB objects""... $ac_c" 1>&6
-echo "configure:1109: checking GDB objects" >&5
+echo "configure:1238: checking GDB objects" >&5
 if eval "test \"`echo '$''{'GDB_OBJ'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1119,15 +1248,14 @@ fi
 echo "$ac_t""$GDB_OBJ" 1>&6
 
 SET_LIBS="pcre bz2 z"
-SET_SPECIAL_LDFLAGS=
 if test -f $SETOBJ/libeasyd.a; then
   SET_LIBS="$SET_LIBS easyd settv"
 else
-  SET_SPECIAL_LDFLAGS="$SET_OBJ/easydiag.a"
+  SET_SPECIAL_LDFLAGS="$SET_SPECIAL_LDFLAGS $SET_OBJ/easydiag.a"
 fi
 
 echo $ac_n "checking for BZ2_bzlibVersion in -lbz2""... $ac_c" 1>&6
-echo "configure:1131: checking for BZ2_bzlibVersion in -lbz2" >&5
+echo "configure:1259: checking for BZ2_bzlibVersion in -lbz2" >&5
 ac_lib_var=`echo bz2'_'BZ2_bzlibVersion | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -1135,7 +1263,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lbz2  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 1139 "configure"
+#line 1267 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -1146,7 +1274,7 @@ int main() {
 BZ2_bzlibVersion()
 ; return 0; }
 EOF
-if { (eval echo configure:1150: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1278: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -1176,7 +1304,7 @@ fi
 
 
 echo $ac_n "checking for zlibVersion in -lz""... $ac_c" 1>&6
-echo "configure:1180: checking for zlibVersion in -lz" >&5
+echo "configure:1308: checking for zlibVersion in -lz" >&5
 ac_lib_var=`echo z'_'zlibVersion | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -1184,7 +1312,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lz  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 1188 "configure"
+#line 1316 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -1195,7 +1323,7 @@ int main() {
 zlibVersion()
 ; return 0; }
 EOF
-if { (eval echo configure:1199: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1327: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -1225,7 +1353,7 @@ fi
 
 
 echo $ac_n "checking for pcre_version in -lpcre""... $ac_c" 1>&6
-echo "configure:1229: checking for pcre_version in -lpcre" >&5
+echo "configure:1357: checking for pcre_version in -lpcre" >&5
 ac_lib_var=`echo pcre'_'pcre_version | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -1233,7 +1361,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lpcre  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 1237 "configure"
+#line 1365 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -1244,7 +1372,7 @@ int main() {
 pcre_version()
 ; return 0; }
 EOF
-if { (eval echo configure:1248: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1376: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -1430,12 +1558,14 @@ s%@host_vendor@%$host_vendor%g
 s%@host_os@%$host_os%g
 s%@rhide_OS@%$rhide_OS%g
 s%@abs_srcdir@%$abs_srcdir%g
-s%@LIB_INTL@%$LIB_INTL%g
+s%@CONIO_PATCH@%$CONIO_PATCH%g
 s%@TV_INC@%$TV_INC%g
 s%@TVOBJ@%$TVOBJ%g
 s%@SETSRC@%$SETSRC%g
 s%@SETOBJ@%$SETOBJ%g
+s%@LIB_INTL@%$LIB_INTL%g
 s%@GDB_SRC@%$GDB_SRC%g
+s%@GDB_SRC_OLD@%$GDB_SRC_OLD%g
 s%@GDB_OBJ@%$GDB_OBJ%g
 s%@SET_SPECIAL_LDFLAGS@%$SET_SPECIAL_LDFLAGS%g
 s%@SET_LIBS@%$SET_LIBS%g
@@ -1545,6 +1675,7 @@ EOF
 chmod +x $CONFIG_STATUS
 rm -fr confdefs* $ac_clean_files
 test "$no_create" = yes || ${CONFIG_SHELL-/bin/sh} $CONFIG_STATUS || exit 1
+
 
 
 $abs_srcdir/configure.sub $abs_srcdir
